---
# The name of the plugin; official plugins always start "jellyfin-plugin-"
name: "jellyfin-plugin-enigma2"

# The GUID of the plugin, found in Plugin.cs
guid: "193f29f9-ea6c-4595-a6f6-55e79d7c590a"

# The version of the plugin, starting at 1. Note that the AssemblyVersion
# and FileVersion flags in the `.csproj` file must have two additional
# fiels, e.g. 1.0.0 to be built correctly.
version: "5.0.2.0" # Please increment with each pull request

# The supported Jellyfin version, usually the earliest binary-compatible
# version. Based on the Jellyfin components from NuGet.
targetAbi: "10.8.0.0" # The earliest binary-compatible version

framework: "net6.0"

# The owner name of the plugin, "jellyfin" for official plugins. Change
# to your own name if you wish to remain a 3rd-party plugin.
owner: "knackebrot"

# A short description of the plugin
overview: "Enigma2"

# A longer and more detailed description of the plugin; use multiple
# lines as required for readability.
description: >
  Live TV plugin for watching Enigma 2 channels and recordings

# The plugin category, in a general sense. These fields are dynamic.
category: "Live TV"

# A list of built artifacts to be bundled into the ZIP for installation.
# Include the main output file, as well as any dependency `.dll`s that
# might be required for the plugin to run.
artifacts:
  - "Jellyfin.Plugin.Enigma2.dll"

# Build information values for the build infrastructure; these should
# not need to be changed usually.
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "net6.0"
